More common types deserializers
alenkacz/postgres-scala pull request #4
Opened 2017-02-12 12:15 UTC by alenkacz

2017-02-12 15:16 UTC, augi commented on src/main/scala/cz/alenkacz/db/postgresscala/DbValue.scala
> +  def dateTime: Instant
I would name it `instant`

2017-02-12 15:18 UTC, augi commented on src/main/scala/cz/alenkacz/db/postgresscala/PostgresAsyncDbValue.scala
> +  override def strings: Array[String] = value.asInstanceOf[Array[String]]
Are you sure that retype to `Array[String]` works? Just asking, maybe a test would be nice.

2017-02-12 15:19 UTC, augi requested changes
...

2017-02-15 21:15 UTC, alenkacz commented
@augi thanks for forcing me to write integration test, it turned out to be really needed

to make it work, I did even some changes in API so the best thing would probably be to re-review the whole PR, thanks!

2017-02-16 09:15 UTC, augi commented on src/test/scala/cz/alenkacz/db/postgresscala/PostgresqlAsyncIntegrationTest.scala
> +case class TestObject(testString: String, testStringArray: Seq[String])
I would prefer to add more field, ideally all the supported types.

2017-02-19 14:24 UTC, alenkacz commented
@augi all supported types are tested via integration test. Is it OK now?

2017-02-19 15:04 UTC, augi commented on src/main/scala/cz/alenkacz/db/postgresscala/PostgresAsyncDbValue.scala
> +  override def bytes: Seq[Byte] = value.asInstanceOf[Array[Byte]].toList
Would be `toSeq` more efficient than `toList`?

2017-02-19 15:07 UTC, augi commented on src/test/scala/cz/alenkacz/db/postgresscala/PostgresqlAsyncIntegrationTest.scala
> +    createTestTable()
I don't like we have to repeat `createTestTable`. Couldn't it be solved somehow?

2017-02-19 16:00 UTC, alenkacz commented on src/main/scala/cz/alenkacz/db/postgresscala/PostgresAsyncDbValue.scala
> +  override def bytes: Seq[Byte] = value.asInstanceOf[Array[Byte]].toList
the reasoning behind toList was that most of the methods return ArrayBuffer which is mutable and I do not want to expose anything mutable

so I just changed it for this byte array

2017-02-19 16:03 UTC, alenkacz commented
@augi both fixed...

2017-02-19 16:27 UTC, augi commented
👍

2017-02-19 16:27 UTC, augi approved these changes

2017-02-19 16:36 UTC, merged